plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/git"
  - - "@semantic-release/github"
    - successComment: false
      failTitle: false

branches:
  - main
  - name: canary
    prerelease: true
